//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowbreakGachaExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowbreakGachaExport.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonCharacterHistory.
        /// </summary>
        internal static string CommonCharacterHisoryName {
            get {
                return ResourceManager.GetString("CommonCharacterHisoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonWeaponHistory.
        /// </summary>
        internal static string CommonWeaponHistoryName {
            get {
                return ResourceManager.GetString("CommonWeaponHistoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialCharacterHistory.
        /// </summary>
        internal static string SpecialCharacterHistoryName {
            get {
                return ResourceManager.GetString("SpecialCharacterHistoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialWeaponHistory.
        /// </summary>
        internal static string SpecialWeaponHistoryName {
            get {
                return ResourceManager.GetString("SpecialWeaponHistoryName", resourceCulture);
            }
        }
    }
}
