name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  auto-merge-filter-Makstein:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_FILTER_AUTHOR: "Makstein"

  auto-merge-filter-tag-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_LABELS: "automerge"

  auto-merge-filter-tag-autorelease_pending:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_LABELS: "autorelease: pending"
