name: Automerge

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  workflow_dispatch:

jobs:
  auto-merge-filter-author:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        author: ["Makstein", "KirisameVanilla"]
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_FILTER_AUTHOR: ${{ matrix.author }}
          MERGE_LABELS: ""

  auto-merge-filter-Kirisame:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_FILTER_AUTHOR: "KirisameVanilla"
          MERGE_LABELS: ""

  auto-merge-filter-tag-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_LABELS: "automerge"
