# implemented by KirisameVanilla

name: Auto-Build

on:
  push:
    branches: ["main"]
    paths:
      - "**.cs"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install .NET CORE
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: |
          msbuild SnowbreakToolbox.sln /t:Restore /p:Configuration=Release

      - name: Build
        run: |
          msbuild SnowbreakToolbox.sln /t:publish /p:Configuration=Release
          tree /f

      - name: Create Zip File
        run: |
          cd SnowbreakToolbox/bin/Release/net8.0-windows/win-x64/publish
          7z a -tzip SnowbreakToolBox.zip .

      - name: Create Release
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: simple
          package-name: standard-version
          changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} SnowbreakToolbox/bin/Release/net8.0-windows/win-x64/publish/SnowbreakToolBox.zip
